#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2017 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    disabled_plugins = ['nerdcommenter']

# Enable autocomplete layer
#[[layers]]
#name = 'autocomplete'
#auto_completion_return_key_behavior = "complete"
#auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'bottom'
default_height = 30

[[layers]]
name = "git"
git-plugin = "fugitive"

[[layers]]
name = "VersionControl"
enable-gtm-status = true

[[layers]]
name = "ui"

[[layers]]
name = "leaderf"

[[layers]]
name = "lang#markdown"

[[layers]]
name = "format"

[[layers]]
name = "lang#java"

[[layers]]
name = "lsp"
filetypes = ["java"]
[layers.override_cmd]
java = [
  "java",
    "-Declipse.application=org.eclipse.jdt.ls.core.id1",
    "-Dosgi.bundles.defaultStartLevel=4",
    "-Declipse.product=org.eclipse.jdt.ls.core.product",
    "-Dlog.protocol=true",
    "-Dlog.level=NONE",
    "-noverify",
    "-Xmx1G",
    "-jar",
    "C:\\Users\\echnzxx\\.SpaceVim.d\\jdt-language-server-latest\\plugins\\org.eclipse.equinox.launcher_1.5.700.v20200207-2156.jar",
    "-configuration",
    "D:\\dev\\jdt-language-server-latest\\config_win",
    "-data",
    "C:\\Users\\echnzxx\\.cache\\javalsp"
]

[[layers]]
name = "lang#c"
filetypes = [
  "c",
  "cpp"
]
[layers.override_cmd]
c = ["clangd"]

[[layers]]
name = "lang#go"


[[layers]]
name = "lang#python"
